### PR TITLE
adds rank to the player sheet

### PR DESCRIPTION
**Pull request by kabobrocks**
Added Rank to the player sheet to stop the complaining. In the future I might look at changing the number to say what it actually is. Left the MMR in the data in case we want to put it back in there (although for now it is out of date) or if Valve gives us the ability to pull it again

### CODE REVIEW

**Review by philkjacobs — COMMENTED** [review]
Wouldn't we want adjusted_rank too?  

https://github.com/seal-dota/server/blob/master/src/repos/player.js

**Comment by kabobrocks** [comment]
@philkjacobs thanks I forgot we sometimes use that

**Review by philkjacobs — APPROVED** [review]
lets find out if I even have permission to accept and merge 👍

**Comment by philkjacobs** [comment]
WAOW

I can approve, but I can't merge.

**Pull request merged**
